#!/bin/bash
# ╔══════════════════════════════════════════════════════════════════════╗
# ║  rebrand.sh — Rebrand "Kaku" -> "Steklo" on a fresh upstream clone ║
# ╚══════════════════════════════════════════════════════════════════════╝
#
# Usage:
#   git clone https://github.com/tw93/Kaku && cd Kaku
#   bash scripts/rebrand.sh
#
# Prerequisites: macOS with Xcode CLT (sed, tic), Rust toolchain (cargo)
#
# This script is designed to be re-run on a fresh upstream pull.
# It is idempotent: it skips renames that have already been applied.
#
# What it does NOT touch (exclusions):
#   - deps/           Git submodules (harfbuzz, freetype) — contain "KIKAKUI"
#                     (a Unicode script name), not project branding
#   - target/         Build artifacts (regenerated by cargo)
#   - .git/           Git internals
#   - Cargo.lock      Regenerated by cargo after crate renames
#   - unicode_names.rs   Unicode character names containing "KIKAKUI"
#   - crates/bidi/    Unicode bidirectional data containing "KIKAKUI"
#   - Binary files    Images, compiled terminfo, etc.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ─── Configuration ──────────────────────────────────────────────────────
OLD_LOWER="kaku"      NEW_LOWER="steklo"
OLD_TITLE="Kaku"      NEW_TITLE="Steklo"
OLD_UPPER="KAKU"      NEW_UPPER="STEKLO"

# ─── Helpers ────────────────────────────────────────────────────────────
log()  { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
step() { printf '\033[0;36m  -> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m  !! %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m  OK %s\033[0m\n' "$*"; }
fail() { printf '\033[1;31m  FAIL %s\033[0m\n' "$*"; exit 1; }

rename_if_exists() {
  local src="$1" dst="$2"
  if [ -e "$src" ]; then
    mkdir -p "$(dirname "$dst")"
    mv "$src" "$dst"
    step "renamed: $src -> $dst"
  fi
}

# ════════════════════════════════════════════════════════════════════════
#  STAGE 1: Content replacements (while files are still at old paths)
# ════════════════════════════════════════════════════════════════════════
log "Stage 1/5: Content replacements in all source files"

# Determine which sed is available (macOS BSD vs GNU)
if sed --version 2>/dev/null | grep -q GNU; then
  sedi() { sed -i "$@"; }
else
  sedi() { sed -i '' "$@"; }
fi

# Collect all text files that contain "kaku" (case-insensitive),
# excluding known false-positive directories and binary files.
step "scanning for files containing 'kaku'..."

REPLACE_FILES=()
while IFS= read -r -d '' file; do
  REPLACE_FILES+=("$file")
done < <(
  find "$REPO_ROOT" -type f \
    -not -path '*/deps/*' \
    -not -path '*/target/*' \
    -not -path '*/.git/*' \
    -not -name 'Cargo.lock' \
    -not -path '*/unicode_names.rs' \
    -not -path '*/crates/bidi/data/*' \
    -not -path '*/crates/bidi/src/bidi_class.rs' \
    -not -name '*.jpeg' -not -name '*.jpg' \
    -not -name '*.png'  -not -name '*.gif' \
    -not -name '*.ico'  -not -name '*.icns' \
    -not -name '*.woff' -not -name '*.woff2' \
    -not -name '*.ttf'  -not -name '*.otf' \
    -not -name '*.dylib' -not -name '*.so' -not -name '*.a' \
    -not -name '*.o' \
    -not -name 'rebrand.sh' \
    -print0 2>/dev/null
)

# Also exclude the compiled terminfo binary (it's not a text file).
# We will recompile it from the .terminfo source later.
COMPILED_TERMINFO="$REPO_ROOT/termwiz/data/${OLD_LOWER}"

COUNT=0
for file in "${REPLACE_FILES[@]}"; do
  # Skip compiled terminfo binary
  [ "$file" = "$COMPILED_TERMINFO" ] && continue

  # Skip files that don't actually contain any variant
  if ! grep -qiI "$OLD_LOWER" "$file" 2>/dev/null; then
    continue
  fi

  # Apply all three case-variant replacements in a single sed pass.
  # Order matters: bundle ID (most specific) first, then general patterns.
  sedi \
    -e "s|fun\.tw93\.${OLD_LOWER}|fun.tw93.${NEW_LOWER}|g" \
    -e "s|${OLD_LOWER}|${NEW_LOWER}|g" \
    -e "s|${OLD_TITLE}|${NEW_TITLE}|g" \
    -e "s|${OLD_UPPER}|${NEW_UPPER}|g" \
    "$file"

  COUNT=$((COUNT + 1))
done

ok "$COUNT files updated"


# ════════════════════════════════════════════════════════════════════════
#  STAGE 1b: Replace ASCII art logos
# ════════════════════════════════════════════════════════════════════════
# The Kaku ASCII art spells "Kaku" in block letters without containing the
# literal string, so the general sed pass above does not catch it.
# We replace it with a "Steklo" FIGlet-style logo in both locations.
log "Stage 1b/5: Replace ASCII art logos"

# Helper: replace N lines starting at the first line matching a pattern.
# Usage: replace_lines_at <file> <grep-pattern> <count> <replacement-file>
replace_lines_at() {
  local file="$1" pattern="$2" count="$3" replacement="$4"
  local line_num total end_line
  line_num=$(grep -n "$pattern" "$file" | head -1 | cut -d: -f1)
  [ -z "$line_num" ] && return 1
  total=$(wc -l < "$file")
  end_line=$((line_num + count - 1))
  {
    head -n $((line_num - 1)) "$file"
    cat "$replacement"
    tail -n $((total - end_line)) "$file"
  } > "${file}.tmp" && mv "${file}.tmp" "$file"
}

# --- first_run.sh (6 echo lines -> 5 echo lines) ---
FIRST_RUN="$REPO_ROOT/assets/shell-integration/first_run.sh"

if [ -f "$FIRST_RUN" ] && grep -q '_  __      _' "$FIRST_RUN"; then
  ART_TMP=$(mktemp)
  cat > "$ART_TMP" << 'SHELL_ART'
echo "  ____  _       _    _       "
echo " / ___|| |_ ___| | _| | ___  "
echo " \___ \| __/ _ \ |/ / |/ _ \ "
echo "  ___) | ||  __/   <| | (_) |"
echo " |____/ \__\___|_|\_\_|\___/ "
SHELL_ART
  replace_lines_at "$FIRST_RUN" '_  __      _' 6 "$ART_TMP"
  rm "$ART_TMP"
  ok "replaced ASCII art in first_run.sh"
else
  step "first_run.sh: ASCII art already replaced or not found"
fi

# --- main.rs (14-line push_str block -> 11-line block) ---
# Try pre-rename path first, then post-rename
MAIN_RS="$REPO_ROOT/${OLD_LOWER}/src/main.rs"
[ ! -f "$MAIN_RS" ] && MAIN_RS="$REPO_ROOT/${NEW_LOWER}/src/main.rs"

if [ -f "$MAIN_RS" ] && grep -q '_  __      _' "$MAIN_RS"; then
  ART_TMP=$(mktemp)
  # Note: Rust string escaping — \\ in source = literal \ in output.
  # The {purple_bold} etc. are format!() arguments, not literal braces.
  # Using multiline format!() style to match rustfmt conventions.
  cat > "$ART_TMP" << 'RUST_ART'
        out.push_str(&format!(
            "{purple_bold}  ____  _       _    _       {reset}\r\n"
        ));
        out.push_str(&format!(
            "{purple_bold} / ___|| |_ ___| | _| | ___  {reset}\r\n"
        ));
        out.push_str(&format!(
            "{purple_bold} \\___ \\| __/ _ \\ |/ / |/ _ \\ {reset}\r\n"
        ));
        out.push_str(&format!(
            "{purple_bold}  ___) | ||  __/   <| | (_) |{reset}  {blue}https://github.com/tw93/Steklo{reset}\r\n"
        ));
        out.push_str(&format!(
            "{purple_bold} |____/ \\__\\___|_|\\_\\_|\\___/ {reset}  {gray}A fast, out-of-the-box terminal built for AI coding.{reset}\r\n"
        ));
RUST_ART
  replace_lines_at "$MAIN_RS" '_  __      _' 14 "$ART_TMP"
  rm "$ART_TMP"
  ok "replaced ASCII art in main.rs"
else
  step "main.rs: ASCII art already replaced or not found"
fi


# ════════════════════════════════════════════════════════════════════════
#  STAGE 2: Recompile terminfo
# ════════════════════════════════════════════════════════════════════════
log "Stage 2/5: Recompile terminfo database"

TERMINFO_SRC="$REPO_ROOT/termwiz/data/${OLD_LOWER}.terminfo"
TERMINFO_SRC_NEW="$REPO_ROOT/termwiz/data/${NEW_LOWER}.terminfo"
TERMINFO_BIN="$REPO_ROOT/termwiz/data/${OLD_LOWER}"
TERMINFO_BIN_NEW="$REPO_ROOT/termwiz/data/${NEW_LOWER}"

# The .terminfo source was already updated by Stage 1.
# Now rename the source file.
if [ -f "$TERMINFO_SRC" ]; then
  mv "$TERMINFO_SRC" "$TERMINFO_SRC_NEW"
  step "renamed terminfo source: ${OLD_LOWER}.terminfo -> ${NEW_LOWER}.terminfo"
fi

# Remove old compiled binary.
if [ -f "$TERMINFO_BIN" ]; then
  rm "$TERMINFO_BIN"
  step "removed old compiled terminfo: ${OLD_LOWER}"
fi

# Recompile from the updated source.
if [ -f "$TERMINFO_SRC_NEW" ]; then
  TMPDIR_TIC=$(mktemp -d)
  if tic -o "$TMPDIR_TIC" -x "$TERMINFO_SRC_NEW" 2>/dev/null; then
    # tic outputs to $TMPDIR_TIC/<first-char-or-hex>/<name>
    COMPILED=$(find "$TMPDIR_TIC" -type f -name "$NEW_LOWER" 2>/dev/null | head -1)
    if [ -n "$COMPILED" ]; then
      cp "$COMPILED" "$TERMINFO_BIN_NEW"
      ok "compiled new terminfo: ${NEW_LOWER}"
    else
      # Fallback: look for any file in the temp dir
      COMPILED=$(find "$TMPDIR_TIC" -type f 2>/dev/null | head -1)
      if [ -n "$COMPILED" ]; then
        cp "$COMPILED" "$TERMINFO_BIN_NEW"
        ok "compiled new terminfo: ${NEW_LOWER} (fallback lookup)"
      else
        warn "tic produced no output — terminfo may need manual recompilation"
      fi
    fi
  else
    warn "tic failed — terminfo may need manual recompilation"
  fi
  rm -rf "$TMPDIR_TIC"
else
  warn "terminfo source not found at $TERMINFO_SRC_NEW"
fi


# ════════════════════════════════════════════════════════════════════════
#  STAGE 3: File and directory renames
# ════════════════════════════════════════════════════════════════════════
log "Stage 3/5: Rename files and directories"

# --- Files inside directories that will be renamed ---
# (Must happen BEFORE their parent directories are renamed)

# Inside Kaku.app bundle
rename_if_exists \
  "assets/macos/${OLD_TITLE}.app/Contents/Resources/${OLD_LOWER}.lua" \
  "assets/macos/${OLD_TITLE}.app/Contents/Resources/${NEW_LOWER}.lua"

# --- Directories ---
rename_if_exists "assets/macos/${OLD_TITLE}.app" \
                 "assets/macos/${NEW_TITLE}.app"

rename_if_exists "assets/macos/${OLD_TITLE}.entitlements" \
                 "assets/macos/${NEW_TITLE}.entitlements"

# Shell completion / integration
rename_if_exists "assets/shell-completion/_${OLD_LOWER}" \
                 "assets/shell-completion/_${NEW_LOWER}"

rename_if_exists "assets/shell-integration/${OLD_LOWER}.sh" \
                 "assets/shell-integration/${NEW_LOWER}.sh"

# Assets
rename_if_exists "assets/${OLD_LOWER}.jpeg" \
                 "assets/${NEW_LOWER}.jpeg"

# Crate directories (the big ones)
rename_if_exists "${OLD_LOWER}-gui" "${NEW_LOWER}-gui"
rename_if_exists "${OLD_LOWER}"     "${NEW_LOWER}"

# OpenCode skill directories
rename_if_exists ".opencode/skills/build-${OLD_LOWER}" \
                 ".opencode/skills/build-${NEW_LOWER}"
rename_if_exists ".opencode/skills/debug-${OLD_LOWER}" \
                 ".opencode/skills/debug-${NEW_LOWER}"

ok "all renames complete"


# ════════════════════════════════════════════════════════════════════════
#  STAGE 4: Regenerate Cargo.lock
# ════════════════════════════════════════════════════════════════════════
log "Stage 4/5: Regenerate Cargo.lock"

# Remove stale lockfile (it references old crate names + hashes)
rm -f "$REPO_ROOT/Cargo.lock"
step "removed old Cargo.lock"

if command -v cargo &>/dev/null; then
  if cargo generate-lockfile 2>&1; then
    ok "Cargo.lock regenerated"
  else
    warn "cargo generate-lockfile failed — run manually after fixing any issues"
  fi
else
  warn "cargo not found — run 'cargo generate-lockfile' manually"
fi


# ════════════════════════════════════════════════════════════════════════
#  STAGE 5: Verification
# ════════════════════════════════════════════════════════════════════════
log "Stage 5/5: Verification"

# --- Check for remaining references ---
step "checking for remaining '${OLD_LOWER}' references..."

REMAINING_FILES=$(
  grep -rl -i "${OLD_LOWER}" \
    --include='*.rs' --include='*.toml' --include='*.sh' \
    --include='*.lua' --include='*.yml' --include='*.yaml' \
    --include='*.md' --include='*.plist' \
    "$REPO_ROOT" 2>/dev/null |
  grep -v '/deps/' |
  grep -v '/target/' |
  grep -v '/.git/' |
  grep -v 'Cargo.lock' |
  grep -v 'unicode_names.rs' |
  grep -v 'crates/bidi/' |
  grep -v 'rebrand.sh' || true
)

if [ -n "$REMAINING_FILES" ]; then
  REMAINING_COUNT=$(echo "$REMAINING_FILES" | wc -l | tr -d ' ')
  warn "$REMAINING_COUNT files still contain '${OLD_LOWER}' references:"
  echo "$REMAINING_FILES" | while read -r f; do
    echo "    $f"
  done
else
  ok "no remaining '${OLD_LOWER}' references in source files"
fi

# --- Check critical paths exist ---
step "verifying critical paths..."
CRITICAL_PATHS=(
  "${NEW_LOWER}/Cargo.toml"
  "${NEW_LOWER}-gui/Cargo.toml"
  "assets/macos/${NEW_TITLE}.app/Contents/Info.plist"
  "assets/macos/${NEW_TITLE}.app/Contents/Resources/${NEW_LOWER}.lua"
  "assets/shell-completion/_${NEW_LOWER}"
  "assets/shell-integration/${NEW_LOWER}.sh"
  "termwiz/data/${NEW_LOWER}.terminfo"
)

ALL_OK=true
for path in "${CRITICAL_PATHS[@]}"; do
  if [ ! -e "$REPO_ROOT/$path" ]; then
    warn "MISSING: $path"
    ALL_OK=false
  fi
done

if $ALL_OK; then
  ok "all critical paths verified"
fi

# --- Try a compile check ---
step "running cargo check..."
if command -v cargo &>/dev/null; then
  if cargo check -p "$NEW_LOWER" -p "${NEW_LOWER}-gui" 2>&1; then
    ok "cargo check passed for ${NEW_LOWER} and ${NEW_LOWER}-gui"
  else
    warn "cargo check failed — manual fixes may be needed"
  fi
fi

echo ""
log "Rebrand complete: ${OLD_TITLE} -> ${NEW_TITLE}"
echo "  Bundle ID:  fun.tw93.${NEW_LOWER}"
echo "  CLI binary: ${NEW_LOWER}"
echo "  GUI binary: ${NEW_LOWER}-gui"
echo "  Config dir: ~/.config/${NEW_LOWER}/"
echo ""
echo "  Next steps:"
echo "    1. Review any warnings above"
echo "    2. Run: make check   (uses new crate names)"
echo "    3. Run: make test"
echo "    4. Run: make app     (builds ${NEW_TITLE}.app)"
echo ""
